apiVersion: v1
kind: Service
metadata:
  name: xfinite-app
  namespace: default
  labels:
    app: xfinite-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: xfinite-app
